#include <boost/format.hpp>
#include <boost/unordered_map.hpp>
#include <boost/foreach.hpp>
#include <boost/scoped_array.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/signals2.hpp>
#include <boost/filesystem.hpp>

#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <set>
#include <algorithm>
#include <queue>
#include <deque>
#include <functional>
#include <mutex>
#include <chrono>
#include <ctime>
#include <iomanip>
#include <limits>
#include <memory>
#include <exception>
#include <thread>
#include <condition_variable>
#include <future>
#include <atomic>
#include <chrono>
#include <iomanip>
#include <unordered_map>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/constants.hpp>
#include <glm/gtx/color_space.hpp>
#include <SFML/Graphics.hpp>